const models = require('../models');

exports.seed = function (knex, Promise) {
  return knex('projects').insert([
    {name: 'The Haunted Swordsman: A Ghost Story Puppet Film',
      short_description: 'In this handcrafted epic puppet film, a lone samurai and his odd companion, a cursed severed head, seek vengeance in a haunted world.',
      long_description: 'The Haunted Swordsman is a live action samurai tale set in a world of demons and ghosts that will utilize 36 inch tall bunraku puppets, traditional in-camera effects and good old-fashioned smoke and mirrors trickery. This short film is only a single chapter in an epic tale of a lone samurai and his odd guide, the cursed severed head of another samurai, as they traverse a world of mythical creatures and nightmares of folklore...  Lost in a bamboo forest, his Shogun murdered by an evil supernatural force, a lone samurai collapses to his knees with an anguished cry. Disgraced and humiliated at having failed to save his Master, the Samurai prepares to commit seppuku. But a voice stops him. A voice emanating from a cursed severed head who offers to guide the Samurai on a quest for vengeance. Thus begins the tale of...The Haunted Swordsman.',
      location: 'Seattle, WA',
      video_url: 'https://www.youtube.com/watch?v=YDXOioU_OKM',
      photo_url: 'http://res.cloudinary.com/dyrrwpemp/image/upload/v1505945255/ndmz05yesufqvozc2d1i.jpg',
      goal_amount: 8000,
      goal_deadline: '11/20/2017',
      upvote_count: 0,
      raised_amount: 0,
      creator_id: 1,
      genre: 'Action'},
    {name: 'Anxiety\'s Wilma:',
      short_description: 'A short romantic comedy about a young woman and her anxiety.',
      long_description: 'I wrote ANXIETY\'S WILMA after watching a series of romantic short films that helped relieve me of some crippling anxiety.  I understand that a short film can\'t magically fix mental health issues, but I do believe the way we talk about/represent mental health plays a big part in how we learn to take care of ourselves. My intent with this short film is to romanticize anxiety for people who struggle with it so that at the very least anxiety starts to feel less like the monster under the bed and more like someone we can get to know. ANXIETY\'S WILMA is about a young woman who gets an opportunity to communicate with her anxiety only to discover that her anxiety needs something from her.',
      location: 'San Francisco, CA',
      photo_url: 'http://res.cloudinary.com/dyrrwpemp/image/upload/v1505945705/voiav8scsxsemgeubxur.jpg',
      video_url: 'https://youtu.be/0roUuwYOYYI',
      goal_amount: 3500,
      goal_deadline: '10/08/2017',
      raised_amount: 0,
      creator_id: 2,
      upvote_count: 0,
      genre: 'Drama'},
    {name: 'Pretty Strong: All Your Favorite Climbing Chicks in One Film',
      short_description: 'Sequi et repudiandae quaerat earum doloribus ut.',
      long_description: 'A full-length climbing film featuring women front and center.',
      location: 'Los Angeles, CA',
      video_url: 'https://www.youtube.com/watch?v=kLf1yQymwrM',
      photo_url: 'http://res.cloudinary.com/dyrrwpemp/image/upload/v1505945894/juu0f4nowwbnremoqd5w.jpg',
      goal_amount: 2500,
      goal_deadline: '10/10/2017',
      upvote_count: 0,
      raised_amount: 0,
      creator_id: 3,
      genre: 'Documentary'},
    {name: 'The Last Knock: A Short Film About the Last Man on Earth',
      short_description: 'A look into the necessity of social interaction within human beings through the eyes of the last man on earth.',
      long_description: 'As the last man on earth, John must utilize an audio recorder as a replacement of human interaction and companionship. Time progresses and John gradually strays away from his original purpose to search for humanity until he encounters scraps of a small campfire. Thus, John must ask himself if he is ready to see another human being? Is he ready to open the door?',
      location: 'Chicago, IL',
      video_url: 'https://youtu.be/YOkUjVV17sY',
      photo_url: 'http://res.cloudinary.com/dyrrwpemp/image/upload/v1505946022/wbb0mgyduetxqvfjyziw.png',
      goal_amount: 3000,
      goal_deadline: '10/20/2017',
      upvote_count: 0,
      raised_amount: 0,
      creator_id: 4,
      genre: 'Comedy'},
    {name: 'A Stitch In Time',
      short_description: 'A short psychological drama about a young man\'s decision to take revenge or make a better choice.',
      long_description: 'A STITCH IN TIME is a psychological drama played out inside a hospital cubicle, where Tony is navigating a situation that will mark his future. Tony, arrives in A&E, cut and stressed out. His friend stabbed, and garbled text messages from his friends as company, Tony concludes that Jay’s aggressor; has arrived in the cubical next-door. Confused and agitated Tony is trying to decide how or even if he should exact revenge. On meeting fellow patient Ant, Tony’s battle receives knowing and unexpected intervention.',
      location: 'New York, NY',
      video_url: 'https://youtu.be/2REkk9SCRn0',
      photo_url: 'http://res.cloudinary.com/dyrrwpemp/image/upload/v1505946463/tsdm2c8sh2c6ptownndb.jpg',
      goal_amount: 2500,
      goal_deadline: '10/28/2017',
      upvote_count: 0,
      raised_amount: 0,
      creator_id: 5,
      genre: 'Drama'},
    {name: 'The Arbors',
      short_description: 'A sci-fi feature film about a lonely man who discovers a mysterious small creature that soon grows to consume his life.',
      long_description: 'As a tight team coming straight out of UNCSA\'s School of Filmmaking program, we’ve been fortunate enough to collaborate on some festival award-winning short films both through the school and independently. From the prep, production through post-production, we’ve been fortunate to work underneath large-scale productions (up to 70-member crews) while also operating under small run-and–gun guerrilla film shoots, such as this film. As a strong, passionate group, we love telling stories in a wide variety of genres, ranging from quirky comedies to Sci-Fi and horror.',
      location: 'Washington, DC',
      video_url: 'https://youtu.be/T54igmon0Vw',
      photo_url: 'http://res.cloudinary.com/dyrrwpemp/image/upload/v1505946319/g1ayd1nm9ra3aabcslco.jpg',
      goal_amount: 3500,
      goal_deadline: '11/01/2017',
      upvote_count: 0,
      raised_amount: 0,
      creator_id: 6,
      genre: 'Science Fiction'},
    {name: 'Web Series About San Francisco Millennial Life',
      short_description: 'unscripted web series centered around Millennial lifestyle in San Francisco, CA',
      long_description: 'The timing to create original web series could not be better. Facebook announced its new Watch tab destined to become the hub of digital media. When combined with the lack of content about life in the Bay Area, advertisers fleeing for digital, and most notably, a generation still just as neurotic as ever, it’s clear there is an opportunity. We are now fundraising to cover equipment, staffing, marketing, legal, and other expenses to help us continue to produce high-quality content for a diverse audience.',
      location: 'San Francisco,CA',
      video_url: 'https://youtu.be/i0dp5wPvi8E',
      photo_url: 'http://res.cloudinary.com/dyrrwpemp/image/upload/v1505944945/ntsmhjnqtixfrdmtguvc.jpg',
      goal_amount: 2000,
      goal_deadline: '11/10/2017',
      upvote_count: 0,
      raised_amount: 0,
      creator_id: 7,
      genre: 'Documentary'},
    {name: 'The Big, Mad, Swim Around Britain',
      short_description: 'A recovering aquaphobe attempts a world-first 1800 mile swim around Britain\'s coast in this inspiring documentary.',
      long_description: 'A woman recovering from 30 years of overwhelming anxiety and fear must beat her lifetime aquaphobia to become the first person ever to swim the full 1800 miles of open water around the coast of mainland Britain. The Big, Mad Swim Movie will tell this incredible story and take you on the journey around Britain by her terrified side. Paula McGuire is the recluse turned adventurer, who used adventure and risk to overcome debilitating social anxiety and depression, and become the woman who gives fear nightmares. Trying everything from wrestling with Olympians to life modelling for artists – and all the wingwalking in between – Paula now spends all that nervous energy helping others to find their barriers and clamber on over them. ',
      location: 'London, UK',
      photo_url: 'http://res.cloudinary.com/dyrrwpemp/image/upload/v1505946790/qweurmi37qtqjc0yiyhv.jpg',
      video_url: 'https://www.youtube.com/watch?v=JyfbFBDnKYM',
      goal_amount: 5000,
      goal_deadline: '10/29/2017',
      raised_amount: 0,
      creator_id: 9,
      upvote_count: 0,
      genre: 'Documentary'},
    {name: 'The Holy Ghost Zone',
      short_description: 'A ghost story like no other',
      long_description: 'Youthful Stephanie enters the Holy Ghost Zone, while her boyfriend, Emmanuel, receives unlikely guidance as he prepares to enter the wilderness. A mixture of rapture and disenchantment, The Holy Ghost Zone follows the inner experiences of two believers at opposite ends of the spiritual spectrum.',
      location: 'Portand, OR',
      photo_url: 'http://res.cloudinary.com/dyrrwpemp/image/upload/v1505939629/ds95r70jnvdiu498zinm.jpg',
      video_url: 'https://www.youtube.com/watch?v=JyfbFBDnKYM',
      goal_amount: 7500,
      goal_deadline: '10/25/2017',
      raised_amount: 0,
      creator_id: 10,
      upvote_count: 0,
      genre: 'Drama'},
    {name: 'The Chills',
        short_description: 'A documentary that journeys to the heart of one of New Zealand music\'s most dramatic stories, Martin Phillipps and The Chills.',
        long_description: 'Late last year, we were filming with The Chills lead singer Martin Phillipps when he was informed he had a 30% chance of dying within six to twelve months if he did not make substantial lifestyle changes. His subsequent decision to reconcile with the world and confront past mistakes has provided the foundation for a compelling and dramatic documentary narrative. Martin has been called a lyrical genius and he and The Chills are credited as one of the founding pioneers of the iconic Dunedin Sound - the ground-breaking musical movement that inspired many seminal musicians around the world and helped usher in a new-found sense of cultural worth in New Zealand. Life has been rocky for this influential musician, he has battled with addiction and depression and it’s taken an exacting toll on his health. Despite the setbacks though Martin has retained an unrelenting commitment to the music and his meticulous collection of pop culture, music and art.',
        location: 'Dunedin, NZ',
        photo_url: 'http://res.cloudinary.com/dyrrwpemp/image/upload/v1505946638/f5cialmqwnlaenpq7i0j.jpg',
        video_url: 'https://www.youtube.com/watch?v=TpGbx4fxogE',
        goal_amount: 7000,
        goal_deadline: '11/01/2017',
        raised_amount: 0,
        creator_id: 8,
        upvote_count: 0,
        genre: 'Documentary'}
  ]);
};

